export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const REGISTERDATA = "REGISTERDATA";
export const RECENTSEARCH = "RECENTSEARCH";
export const RECENTSEARCHREMOVE = "RECENTSEARCHREMOVE";
export const RECENTSEARCHREMOVEALL = "RECENTSEARCHREMOVEALL";
